server:
  port: 8090

spring:
  application:
    name: payment-demo #应用的名字

  Jackson:
    data-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/payment_demo
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  configuration: #sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-location: classpath:com/atguigu/paymentdemo/mapper/xml/*.xml